### ISSUE TITLE
[BUG] Form fields that are not required/supposed to be editable

### ISSUE THREAD

**Issue by vshekar** [darkreactions/ESCALATE#22]
**Describe the bug**
Not exactly a bug but certain form fields aren't supposed to be editable because they depend on a previous field

**To Reproduce**
![image](https://user-images.githubusercontent.com/7152270/87563180-ef41a800-c68c-11ea-92b1-4c60b833b100.png)
Take for example the person form. It is redundant to have "Organization full name" field because it is read only. If the name is changed to suppose "Haverford123" and submitted it has no effect. The only way to change organization is to use the dropdown menu for "Organization" 

**Expected behavior**
Only updateable fields should be shown in a form. To see which fields are updateable  please refer to the [technical document](https://github.com/darkreactions/ESCALATE/blob/master/data_model/TECHNICAL.md#views) any field that is only a (v) or view should not be shown in the edit/create form.

**Comment by ichang1** [comment]
@vshekar I just noticed that vw_actor is only R, not CRUD. Does that mean we shouldn't have a view that handles adding an actor?

**Comment by vshekar** [comment]
@ichang1 You can fix it but you wont be able to test it i.e. if you submit the form it will crash and that's ok

**Comment by gcatabr1** [comment]
@gcatabr1 will provide an updatable vw_actor today. I was waiting until person, org and systemtool forms were settled; so now I need to get on it! I will add a specific [DEV] issue pertaining to an updatable vw_actor...
