### ISSUE TITLE
[DEV] Create Updatable vw_actor

### ISSUE THREAD

**Issue by gcatabr1** [darkreactions/ESCALATE#23]
### ***Development Sprint for: ...***
  - [x] Data Model
  - [ ] UI
  - [ ] API
  - [ ] Functionality
  - [ ] Integration
  - [ ] System
  - [ ] Other - [specify]

***Description of this sprint tasks***
add upsert capability to vw_actor
***Expected Deliverable***
upsert_actor trigger, examples in vw_actor, update technical documentation
***How will this be tested?***
several test examples
***How will this be reviewed?***

***Link(s) to necessary documentation***
  
***Other information***

**Comment by vshekar** [comment]
Realized that to create notes I need to associate person with actor during registration. I'm working on putting the code in place. Will start testing once you add this piece
