### ISSUE TITLE
[DEV]

### ISSUE THREAD

**Issue by HaosongH** [darkreactions/ESCALATE#30]
### ***Development Sprint for: ...***
  - [ ] UI
  - [ ] Functionality

***Description of this sprint tasks***
1. Add person cuncurrently with note
2. add delete all note/tag
3. add tag
***Expected Deliverable***

***How will this be tested?***

***How will this be reviewed?***

***Link(s) to necessary documentation***
  
***Other information***

**Comment by gcatabr1** [comment]
note, tag, udf deletion now automatic
