### ISSUE TITLE
[BUG] add_date, mod_date in vw_actor

### ISSUE THREAD

**Issue by vshekar** [darkreactions/ESCALATE#33]
**Describe the bug**
add_date and mod_date in vw_actor is named actor_add_date and actor_mod_date. All the other views do not have the prefix of its view name. Not urgent, Django can handle any column name and use a different name in code. Pointing out for consistency

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vshekar** [comment]
Just realized, add_date and mod_date are missing in the latest database views for actor

**Comment by gcatabr1** [comment]
This view is unique in that it comprises and displays several entities / sub-views (organization, person, and systemtool). Thought it would be clearer to identify which columns belong to the actor v the other entities. Perhaps it would be clearer if actor columns have no entity designation... Hmm, on second thought, as I write this, that is what I'll do. Keep the person, organization, and systemtool related columns as is, and keep the actor columns sans 'actor'

**Comment by gcatabr1** [comment]
Will open

**Comment by gcatabr1** [comment]
Reopened to address consistency of actor-related columns in views. The rule-of-thumb will be views that are actor-centric, the actor table columns will not have 'actor' preceding. So actor_description -> description; actor_mod_date -> mod_date. For views that are NOT actor-centric, but with actor columns, the columns will be specified as 'actor_...'. For example, in vw_calculation, actor description will be distinguished from calculation description by: actor_description.
