### ISSUE TITLE
[BUG] Manual Method for escalate

### ISSUE THREAD

**Issue by TellyWu** [darkreactions/ESCALATE#42]
**Describe the bug**
1.When I used "prod_update_3_calculation.sql" , the following error was thrown:
"
ERROR:  column "_calc_chrg_per_asa-" does not exist
LINE 291: ...chrg_per_asa_standardize', '_calc_chrg_per_asa-', "_calc_chr...
                                                               ^
HINT:  Perhaps you meant to reference the column "pd._calc_chrg_per_asa".
SQL state: 42703
Character: 20922
"

**To Reproduce**
1. Go to 'pgAdmin4'
2. Click on 'QueryTool'
3. Scroll down to 'prod_update_3_calculation.sql'
4. Execute
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/70195164/93841416-1a1c2e00-fcc6-11ea-98b5-2ada58dbbc62.png)
![image](https://user-images.githubusercontent.com/70195164/93841328-d1647500-fcc5-11ea-9d69-7abcc0c514e5.png)

**Comment by gcatabr1** [comment]
Probably cause is empty or incomplete `load_perov_desc` table. Ensure the load tables in 'sql_dataload' subdirectory have executed successfully (including presence of '_calc_chrg_per_asa-' column).

![Screen Shot 2020-09-22 at 9 06 18 AM](https://user-images.githubusercontent.com/123806/93886930-07006280-fcb4-11ea-94d8-d0bea9a70c0d.png)
