### ISSUE TITLE
[BUG] Inserting into vw_parameter does not show up on Django

### ISSUE THREAD

**Issue by vshekar** [darkreactions/ESCALATE#57]
**Describe the bug**
A row inserted into vw_parameter via SQL does not show up in the rest api list

**To Reproduce**
1. Checked the number of rows returned from API endpoint http://localhost:8000/api/parameter/ (16 rows)
2. Ran the following SQL statement directly on db
```pgsql
insert into vw_parameter (parameter_def_uuid, ref_parameter_uuid, parameter_val, actor_uuid, status_uuid ) values (
					    (select parameter_def_uuid from vw_parameter_def where description = 'duration'),
                                            (select person_uuid from vw_person where last_name = 'Pendleton'),
					    (select put_val ((select val_type_uuid from vw_parameter_def where description = 'duration'),
								      '10',
					                              (select valunit from vw_parameter_def where description = 'duration'))),
					    (select actor_uuid from vw_actor where org_short_name = 'LANL'),
					    (select status_uuid from vw_status where description = 'active')
											);
```
3. Checked number of rows in endpoint, still 16 rows as before insertion
4. Selected rows from database shows correct number of rows
```pgsql
SELECT * FROM .vw_parameter LIMIT 1000;
```
**Expected behavior**
API endpoint should show inserted row, but doesn't

**Comment by miketynes** [comment]
Copying the `parameter_uuid` from the record created in the DB to `http://localhost:8000/api/parameter/ <uud>` also fails, giving 

```
{
    "detail": "Not found."
}
```

**Comment by miketynes** [comment]
Records inserted into vw_action from the db side are displayed through the API GET as expected, so this is a parameter-specific problem.

**Comment by miketynes** [comment]
06c9c93 should fix it. @vshekar test and confirm?

**Comment by vshekar** [comment]
Fixed
